export * as HealthController from './health.controller'
export * as AuthController from './auth.controller'
export * as FitnessClassController from './fitnessClass.controller'
export * as BookingController from './fitnessClassBooking.controller'
export * as UserController from './user.controller'
export * as InstructorController from './instructor.controller'
